/**
 * Config plugin: limit the Android ABIs that get compiled into the app.
 *
 * WHY THIS EXISTS
 * A default React Native release APK ships native libraries for four
 * architectures. Measured on this project:
 *
 *   arm64-v8a     16.0 MB   real phones (all modern devices)
 *   armeabi-v7a   11.0 MB   older real phones
 *   x86           16.8 MB   emulators only
 *   x86_64        16.4 MB   emulators only
 *
 * That is 60 MB of an 71.6 MB APK, and 33 MB of it can never run on a phone.
 * Proguard/resource shrinking does not touch native libraries, so it only saved
 * ~8 MB on its own — dropping the emulator architectures is the real win.
 *
 * WHY A PLUGIN AND NOT gradle.properties
 * `android/` is gitignored and regenerated by every `expo prebuild`, so editing
 * gradle.properties by hand silently reverts. Config plugins run as part of
 * prebuild, so the setting survives.
 *
 * ⚠️ TRADE-OFF: with x86/x86_64 removed the app will not run on a standard
 * Android emulator on an Intel/AMD machine (Apple Silicon emulators are arm64
 * and still work). If you need emulator testing, add them back to ABIS below
 * and rebuild. For Play Store releases prefer an AAB — Google then delivers
 * only the architecture each device needs, which beats any manual split.
 */
const { withGradleProperties } = require('expo/config-plugins');

/** Architectures we actually ship. Add 'x86','x86_64' back for emulator testing. */
const ABIS = ['armeabi-v7a', 'arm64-v8a'];

const withAndroidAbiFilters = (config) =>
  withGradleProperties(config, (cfg) => {
    const KEY = 'reactNativeArchitectures';

    // Drop any existing definition so we don't end up with duplicate keys — the
    // React Native template ships this property with all four architectures.
    cfg.modResults = cfg.modResults.filter(
      (item) => !(item.type === 'property' && item.key === KEY),
    );

    cfg.modResults.push({
      type: 'comment',
      value: 'Set by plugins/withAndroidAbiFilters.js — emulator ABIs (x86, x86_64) excluded to cut ~33 MB.',
    });
    cfg.modResults.push({ type: 'property', key: KEY, value: ABIS.join(',') });

    return cfg;
  });

module.exports = withAndroidAbiFilters;
